ALTER TABLE drone_models
  ADD COLUMN IF NOT EXISTS drone_group VARCHAR(50) NOT NULL DEFAULT 'recon',
  ADD COLUMN IF NOT EXISTS drone_type VARCHAR(50) NOT NULL DEFAULT 'copter',
  ADD COLUMN IF NOT EXISTS camera_type VARCHAR(50) NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS note TEXT NULL,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE drone_warhead_types
  ADD COLUMN IF NOT EXISTS weight_kg NUMERIC(10, 2) NULL,
  ADD COLUMN IF NOT EXISTS measure_unit VARCHAR(20) NOT NULL DEFAULT 'unit',
  ADD COLUMN IF NOT EXISTS note TEXT NULL,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE depot_drone_stock
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE depot_drone_warhead_stock
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE depot_drone_warhead_stock
  ALTER COLUMN quantity TYPE NUMERIC(18, 3) USING quantity::numeric;

ALTER TABLE air_asset_drone_stock
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE air_asset_warhead_stock
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE air_asset_warhead_stock
  ALTER COLUMN quantity TYPE NUMERIC(18, 3) USING quantity::numeric;

ALTER TABLE drone_stock_movements
  ADD COLUMN IF NOT EXISTS depot_from_id UUID NULL,
  ADD COLUMN IF NOT EXISTS depot_to_id UUID NULL,
  ADD COLUMN IF NOT EXISTS air_asset_from_id UUID NULL,
  ADD COLUMN IF NOT EXISTS air_asset_to_id UUID NULL,
  ADD COLUMN IF NOT EXISTS drone_model_id UUID NULL,
  ADD COLUMN IF NOT EXISTS warhead_type_id UUID NULL,
  ADD COLUMN IF NOT EXISTS quantity INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS comment TEXT NULL,
  ADD COLUMN IF NOT EXISTS created_by_id UUID NULL,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE drone_stock_movements
  ALTER COLUMN quantity TYPE NUMERIC(18, 3) USING quantity::numeric;

ALTER TABLE drone_models
  ADD COLUMN IF NOT EXISTS max_range_m INTEGER NULL,
  ADD COLUMN IF NOT EXISTS cruise_speed_kmh INTEGER NULL,
  ADD COLUMN IF NOT EXISTS endurance_minutes INTEGER NULL,
  ADD COLUMN IF NOT EXISTS payload_capacity_kg NUMERIC(10, 3) NULL,
  ADD COLUMN IF NOT EXISTS max_altitude_m INTEGER NULL,
  ADD COLUMN IF NOT EXISTS max_wind_ms NUMERIC(10, 2) NULL;