ALTER TABLE drone_models
  ADD COLUMN IF NOT EXISTS max_range_m INTEGER NULL,
  ADD COLUMN IF NOT EXISTS cruise_speed_kmh INTEGER NULL,
  ADD COLUMN IF NOT EXISTS endurance_minutes INTEGER NULL,
  ADD COLUMN IF NOT EXISTS payload_capacity_kg NUMERIC(10, 3) NULL,
  ADD COLUMN IF NOT EXISTS max_altitude_m INTEGER NULL,
  ADD COLUMN IF NOT EXISTS max_wind_ms NUMERIC(10, 2) NULL;